// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class MangaPublishDBContext : DbContext
{
    public MangaPublishDBContext(DbContextOptions<MangaPublishDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AssistantProfile> AssistantProfiles { get; set; }

    public virtual DbSet<BoardEvaluation> BoardEvaluations { get; set; }
    public virtual DbSet<BoardEvaluationDetail> BoardEvaluationDetails { get; set; }

    public virtual DbSet<Chapter> Chapters { get; set; }

    public virtual DbSet<Genre> Genres { get; set; }

    public virtual DbSet<IssueResource> IssueResources { get; set; }

    public virtual DbSet<MangakaAssistant> MangakaAssistants { get; set; }

    public virtual DbSet<MangakaProfile> MangakaProfiles { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<Page> Pages { get; set; }

    public virtual DbSet<PageIssue> PageIssues { get; set; }

    public virtual DbSet<Pagelayer> Pagelayers { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Series> Series { get; set; }

    public virtual DbSet<Tag> Tags { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserToken> UserTokens { get; set; }

    public virtual DbSet<WeeklyRanking> WeeklyRankings { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
       => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        foreach (var entityType in modelBuilder.Model.GetEntityTypes())
        {
            // Tìm khóa chính của từng bảng
            var primaryKey = entityType.FindPrimaryKey();
            if (primaryKey != null)
            {
                foreach (var property in primaryKey.Properties)
                {
                    // Nếu khóa chính là kiểu số (int, long)
                    if (property.ClrType == typeof(int) || property.ClrType == typeof(long))
                    {
                        // Ép EF Core coi nó là cột tự tăng do DB quản lý
                        property.ValueGenerated = Microsoft.EntityFrameworkCore.Metadata.ValueGenerated.OnAdd;
                    }
                }
            }
        }
            modelBuilder.Entity<AssistantProfile>(entity =>
        {
            entity.HasKey(e => e.AssistantProfileId).HasName("assistant_profiles_pkey");

            entity.ToTable("assistant_profiles");

            entity.HasIndex(e => e.Userid, "UQ__assistan__CBA1B256DE4910DB").IsUnique();

            entity.Property(e => e.AssistantProfileId).HasColumnName("assistant_profile_id");
            entity.Property(e => e.AvatarUrl).HasColumnName("avatar_url");
            entity.Property(e => e.BankAccountName)
                .HasMaxLength(255)
                .HasColumnName("bank_account_name");
            entity.Property(e => e.BankAccountNumber)
                .HasMaxLength(50)
                .HasColumnName("bank_account_number");
            entity.Property(e => e.BankName)
                .HasMaxLength(100)
                .HasColumnName("bank_name");
            entity.Property(e => e.IsAvailable)
                .HasDefaultValue(true)
                .HasColumnName("is_available");
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(50)
                .HasColumnName("phone_number");
            entity.Property(e => e.PortfolioUrl).HasColumnName("portfolio_url");
            entity.Property(e => e.Skills).HasColumnName("skills");
            entity.Property(e => e.SoftwareUsed).HasColumnName("software_used");
            entity.Property(e => e.Updatedat)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updatedat");
            entity.Property(e => e.Userid).HasColumnName("userid");

            entity.HasOne(d => d.User).WithOne(p => p.AssistantProfile)
                .HasForeignKey<AssistantProfile>(d => d.Userid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("assistant_profiles_userid_fkey");
        });

        modelBuilder.Entity<BoardEvaluationDetail>(entity =>
        {
            entity.HasKey(e => e.DetailId);

            entity.ToTable("board_evaluation_details");

            entity.Property(e => e.DetailId).HasColumnName("detail_id");
            entity.Property(e => e.EvaluationId).HasColumnName("evaluation_id");
            entity.Property(e => e.EbId).HasColumnName("eb_id");

            entity.Property(e => e.StoryScore).HasColumnName("story_score");
            entity.Property(e => e.ArtScore).HasColumnName("art_score");
            entity.Property(e => e.CharacterScore).HasColumnName("character_score");
            entity.Property(e => e.CommercialScore).HasColumnName("commercial_score");
            entity.Property(e => e.PacingScore).HasColumnName("pacing_score");
            entity.Property(e => e.AverageScore)
                            .HasColumnName("average_score")
                            .ValueGeneratedOnAddOrUpdate();

            entity.Property(e => e.Feedback).HasColumnName("feedback");
            entity.Property(e => e.EvaluatedAt).HasColumnName("evaluated_at");

            entity.HasOne(d => d.Evaluation)
                .WithMany(p => p.BoardEvaluationDetails)
                .HasForeignKey(d => d.EvaluationId);

            entity.HasOne(d => d.Eb)
                .WithMany()
                .HasForeignKey(d => d.EbId);
        });

        modelBuilder.Entity<BoardEvaluation>(entity =>
        {
            entity.HasKey(e => e.Evaluationid).HasName("board_evaluations_pkey");

            entity.ToTable("board_evaluations");

            entity.Property(e => e.Evaluationid).HasColumnName("evaluationid");
            entity.Property(e => e.ApprovedPublishFormat)
                .HasMaxLength(50)
                .HasColumnName("approved_publish_format");
            entity.Property(e => e.ArtScore)
                .HasColumnType("decimal(4, 2)")
                .HasColumnName("art_score");
            entity.Property(e => e.AverageScore)
                .HasComputedColumnSql("(CONVERT([decimal](4,2),(((([story_score]+[art_score])+[character_score])+[commercial_score])+[pacing_score])/(5.0)))", false)
                .HasColumnType("decimal(4, 2)")
                .HasColumnName("average_score");
            entity.Property(e => e.CharacterScore)
                .HasColumnType("decimal(4, 2)")
                .HasColumnName("character_score");
            entity.Property(e => e.CommercialScore)
                .HasColumnType("decimal(4, 2)")
                .HasColumnName("commercial_score");
            entity.Property(e => e.Evaluatedat)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("evaluatedat");
            entity.Property(e => e.Feedback).HasColumnName("feedback");
            entity.Property(e => e.FinalDecision)
                .HasMaxLength(50)
                .HasColumnName("final_decision");
            entity.Property(e => e.Inputtedbyid).HasColumnName("inputtedbyid");
            entity.Property(e => e.PacingScore)
                .HasColumnType("decimal(4, 2)")
                .HasColumnName("pacing_score");
            entity.Property(e => e.Seriesid).HasColumnName("seriesid");
            entity.Property(e => e.StoryScore)
                .HasColumnType("decimal(4, 2)")
                .HasColumnName("story_score");

            entity.HasOne(d => d.Inputtedby).WithMany(p => p.BoardEvaluations)
                .HasForeignKey(d => d.Inputtedbyid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("board_evaluations_inputtedbyid_fkey");

            entity.HasOne(d => d.Series).WithMany(p => p.BoardEvaluations)
                .HasForeignKey(d => d.Seriesid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("board_evaluations_seriesid_fkey");
        });

        modelBuilder.Entity<Chapter>(entity =>
        {
            entity.HasKey(e => e.Chapterid).HasName("chapters_pkey");

            entity.ToTable("chapters");

            entity.Property(e => e.Chapterid).HasColumnName("chapterid");
            entity.Property(e => e.Chapternumber).HasColumnName("chapternumber");
            entity.Property(e => e.Createdat)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdat");
            entity.Property(e => e.Deadline)
                .HasColumnType("datetime")
                .HasColumnName("deadline");
            entity.Property(e => e.Isdeleted)
                .HasDefaultValue(false)
                .HasColumnName("isdeleted");
            entity.Property(e => e.Seriesid).HasColumnName("seriesid");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.Title)
                .HasMaxLength(255)
                .HasColumnName("title");

            entity.HasOne(d => d.Series).WithMany(p => p.Chapters)
                .HasForeignKey(d => d.Seriesid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("chapters_seriesid_fkey");
        });

        modelBuilder.Entity<Genre>(entity =>
        {
            entity.HasKey(e => e.Genreid).HasName("genres_pkey");

            entity.ToTable("genres");

            entity.Property(e => e.Genreid).HasColumnName("genreid");
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .HasColumnName("description");
            entity.Property(e => e.Genrename)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("genrename");
        });

        modelBuilder.Entity<IssueResource>(entity =>
        {
            entity.HasKey(e => e.Resourceid).HasName("issue_resources_pkey");

            entity.ToTable("issue_resources");

            entity.Property(e => e.Resourceid).HasColumnName("resourceid");
            entity.Property(e => e.Filename)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("filename");
            entity.Property(e => e.Fileurl)
                .IsRequired()
                .HasColumnName("fileurl");
            entity.Property(e => e.Issueid).HasColumnName("issueid");
            entity.Property(e => e.Uploadedat)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("uploadedat");

            entity.HasOne(d => d.Issue).WithMany(p => p.IssueResources)
                .HasForeignKey(d => d.Issueid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("issue_resources_issueid_fkey");
        });

        modelBuilder.Entity<MangakaAssistant>(entity =>
        {
            entity.HasKey(e => e.ContractId).HasName("mangaka_assistants_pkey");

            entity.ToTable("mangaka_assistants");

            entity.HasIndex(e => new { e.MangakaId, e.AssistantId }, "unique_active_contract").IsUnique();

            entity.Property(e => e.ContractId).HasColumnName("contract_id");
            entity.Property(e => e.AssistantId).HasColumnName("assistant_id");
            entity.Property(e => e.ContractTerms).HasColumnName("contract_terms");
            entity.Property(e => e.Createdat)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdat");
            entity.Property(e => e.EndDate).HasColumnName("end_date");
            entity.Property(e => e.MangakaId).HasColumnName("mangaka_id");
            entity.Property(e => e.SalaryAmount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("salary_amount");
            entity.Property(e => e.SalaryType)
                .HasMaxLength(50)
                .HasDefaultValue("Monthly")
                .HasColumnName("salary_type");
            entity.Property(e => e.StartDate).HasColumnName("start_date");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("Pending")
                .HasColumnName("status");

            entity.Property(e => e.Isdeleted)
                .HasDefaultValue(false)
                .HasColumnName("isdeleted");

            entity.Property(e => e.ContractFileUrl)
                .HasColumnName("contract_file_url");

            entity.HasOne(d => d.Assistant).WithMany(p => p.MangakaAssistantAssistants)
                .HasForeignKey(d => d.AssistantId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("mangaka_assistants_assistant_fkey");

            entity.HasOne(d => d.Mangaka).WithMany(p => p.MangakaAssistantMangakas)
                .HasForeignKey(d => d.MangakaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("mangaka_assistants_mangaka_fkey");
        });

        modelBuilder.Entity<MangakaProfile>(entity =>
        {
            entity.HasKey(e => e.MangakaProfileId).HasName("mangaka_profiles_pkey");

            entity.ToTable("mangaka_profiles");

            entity.HasIndex(e => e.Userid, "UQ__mangaka___CBA1B256CA1FBED5").IsUnique();

            entity.Property(e => e.MangakaProfileId).HasColumnName("mangaka_profile_id");
            entity.Property(e => e.AvatarUrl).HasColumnName("avatar_url");
            entity.Property(e => e.BankAccountName)
                .HasMaxLength(255)
                .HasColumnName("bank_account_name");
            entity.Property(e => e.BankAccountNumber)
                .HasMaxLength(50)
                .HasColumnName("bank_account_number");
            entity.Property(e => e.BankName)
                .HasMaxLength(100)
                .HasColumnName("bank_name");
            entity.Property(e => e.Bio).HasColumnName("bio");
            entity.Property(e => e.PenName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("pen_name");
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(50)
                .HasColumnName("phone_number");
            entity.Property(e => e.Updatedat)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updatedat");
            entity.Property(e => e.Userid).HasColumnName("userid");

            entity.HasOne(d => d.User).WithOne(p => p.MangakaProfile)
                .HasForeignKey<MangakaProfile>(d => d.Userid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("mangaka_profiles_userid_fkey");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.Notificationid).HasName("notifications_pkey");

            entity.ToTable("notifications");

            entity.Property(e => e.Notificationid).HasColumnName("notificationid");
            entity.Property(e => e.Createdat)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdat");
            entity.Property(e => e.Isread)
                .HasDefaultValue(false)
                .HasColumnName("isread");
            entity.Property(e => e.Message)
                .IsRequired()
                .HasColumnName("message");
            entity.Property(e => e.Seriesid).HasColumnName("seriesid");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("title");
            entity.Property(e => e.Userid).HasColumnName("userid");
            entity.Property(e => e.Referencetype)
                .HasMaxLength(100)
                .HasColumnName("referencetype");
            entity.Property(e => e.Referenceid).HasColumnName("referenceid");

            entity.HasOne(d => d.Series).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.Seriesid)
                .HasConstraintName("notifications_seriesid_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.Userid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("notifications_userid_fkey");
        });

        modelBuilder.Entity<Page>(entity =>
        {
            entity.HasKey(e => e.Pageid).HasName("pages_pkey");

            entity.ToTable("pages");

            entity.Property(e => e.Pageid).HasColumnName("pageid");
            entity.Property(e => e.Chapterid).HasColumnName("chapterid");
            entity.Property(e => e.Isdeleted)
                .HasDefaultValue(false)
                .HasColumnName("isdeleted");
            entity.Property(e => e.Pageimageurl)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("pageimageurl");
            entity.Property(e => e.Pagenumber).HasColumnName("pagenumber");
            entity.Property(e => e.IsSentToMangaka)
                .HasDefaultValue(false)
                .HasColumnName("issenttomangaka");

            entity.HasOne(d => d.Chapter).WithMany(p => p.Pages)
                .HasForeignKey(d => d.Chapterid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("pages_chapterid_fkey");
        });

        modelBuilder.Entity<PageIssue>(entity =>
        {
            entity.HasKey(e => e.Issueid).HasName("page_issues_pkey");

            entity.ToTable("page_issues");

            entity.Property(e => e.Issueid).HasColumnName("issueid");
            entity.Property(e => e.AssignedToId).HasColumnName("assigned_to_id");
            entity.Property(e => e.BoxHeight).HasColumnName("box_height");
            entity.Property(e => e.BoxWidth).HasColumnName("box_width");
            entity.Property(e => e.BoxX).HasColumnName("box_x");
            entity.Property(e => e.BoxY).HasColumnName("box_y");
            entity.Property(e => e.Completedat)
                .HasColumnType("datetime")
                .HasColumnName("completedat");
            entity.Property(e => e.CreatedById).HasColumnName("created_by_id");
            entity.Property(e => e.Createdat)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdat");
            entity.Property(e => e.Deadline)
                .HasColumnType("datetime")
                .HasColumnName("deadline");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnName("description");
            entity.Property(e => e.Isdeleted)
                .HasDefaultValue(false)
                .HasColumnName("isdeleted");
            entity.Property(e => e.IssueType)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("issue_type");
            entity.Property(e => e.Pageid).HasColumnName("pageid");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("Reported")
                .HasColumnName("status");
            entity.Property(e => e.WorkCategory)
                .HasMaxLength(50)
                .HasColumnName("work_category");

            entity.HasOne(d => d.AssignedTo).WithMany(p => p.PageIssueAssignedTos)
                .HasForeignKey(d => d.AssignedToId)
                .HasConstraintName("page_issues_assigned_to_fkey");

            entity.HasOne(d => d.CreatedBy).WithMany(p => p.PageIssueCreatedBies)
                .HasForeignKey(d => d.CreatedById)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("page_issues_created_by_fkey");

            entity.HasOne(d => d.Page).WithMany(p => p.PageIssues)
                .HasForeignKey(d => d.Pageid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("page_issues_pageid_fkey");
        });

        modelBuilder.Entity<Pagelayer>(entity =>
        {
            entity.HasKey(e => e.Layerid).HasName("pagelayers_pkey");

            entity.ToTable("pagelayers");

            entity.Property(e => e.Layerid).HasColumnName("layerid");
            entity.Property(e => e.Createdat)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdat");
            entity.Property(e => e.Fileurl)
                .IsRequired()
                .HasColumnName("fileurl");
            entity.Property(e => e.Isvisible)
                .HasDefaultValue(true)
                .HasColumnName("isvisible");
            entity.Property(e => e.Layername)
                .HasMaxLength(255)
                .HasColumnName("layername");
            entity.Property(e => e.Pageid).HasColumnName("pageid");
            entity.Property(e => e.Uploaderid).HasColumnName("uploaderid");
            entity.Property(e => e.Versionnumber)
                .HasDefaultValue(1)
                .HasColumnName("versionnumber");
            entity.Property(e => e.Zindex)
                .HasDefaultValue(0)
                .HasColumnName("zindex");

            entity.Property(e => e.Opacity)
                .HasColumnType("decimal(3, 2)")
                .HasDefaultValue(1.0m)
                .HasColumnName("opacity");

            entity.Property(e => e.Isdeleted)
                .HasDefaultValue(false)
                .HasColumnName("isdeleted");

            entity.HasOne(d => d.Page).WithMany(p => p.Pagelayers)
                .HasForeignKey(d => d.Pageid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("pagelayers_pageid_fkey");

            entity.HasOne(d => d.Uploader).WithMany(p => p.Pagelayers)
                .HasForeignKey(d => d.Uploaderid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("pagelayers_uploaderid_fkey");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Roleid).HasName("roles_pkey");

            entity.ToTable("roles");

            entity.HasIndex(e => e.Rolename, "UQ__roles__4685A06214B93FA6").IsUnique();

            entity.Property(e => e.Roleid).HasColumnName("roleid");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.Rolename)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("rolename");
        });

        modelBuilder.Entity<Series>(entity =>
        {
            entity.HasKey(e => e.Seriesid).HasName("series_pkey");

            entity.ToTable("series");

            entity.Property(e => e.Seriesid).HasColumnName("seriesid");
            entity.Property(e => e.Agerating)
                .IsRequired()
                .HasMaxLength(10)
                .HasDefaultValue("G")
                .HasColumnName("agerating");
            entity.Property(e => e.Approvedat)
                .HasColumnType("datetime")
                .HasColumnName("approvedat");
            entity.Property(e => e.Coverimageurl)
                .HasMaxLength(500)
                .HasColumnName("coverimageurl");
            entity.Property(e => e.Createdat)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdat");
            entity.Property(e => e.Isdeleted)
                .HasDefaultValue(false)
                .HasColumnName("isdeleted");
            entity.Property(e => e.Mangakaid).HasColumnName("mangakaid");
            entity.Property(e => e.Proposalfileurl).HasColumnName("proposalfileurl");
            entity.Property(e => e.Publishformat)
                .HasMaxLength(50)
                .HasColumnName("publishformat");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.Synopsis).HasColumnName("synopsis");
            entity.Property(e => e.Tantoueditorid).HasColumnName("tantoueditorid");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("title");

            entity.HasOne(d => d.Mangaka).WithMany(p => p.SeriesMangakas)
                .HasForeignKey(d => d.Mangakaid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("series_mangakaid_fkey");

            entity.HasOne(d => d.Tantoueditor).WithMany(p => p.SeriesTantoueditors)
                .HasForeignKey(d => d.Tantoueditorid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("series_tantoueditorid_fkey");

            entity.HasMany(d => d.Genres).WithMany(p => p.Series)
                .UsingEntity<Dictionary<string, object>>(
                    "SeriesGenre",
                    r => r.HasOne<Genre>().WithMany()
                        .HasForeignKey("Genreid")
                        .HasConstraintName("fk_sg_genres"),
                    l => l.HasOne<Series>().WithMany()
                        .HasForeignKey("Seriesid")
                        .HasConstraintName("fk_sg_series"),
                    j =>
                    {
                        j.HasKey("Seriesid", "Genreid").HasName("series_genres_pkey");
                        j.ToTable("series_genres");
                        j.IndexerProperty<int>("Seriesid").HasColumnName("seriesid");
                        j.IndexerProperty<int>("Genreid").HasColumnName("genreid");
                    });

            entity.HasMany(d => d.Tags).WithMany(p => p.Series)
                .UsingEntity<Dictionary<string, object>>(
                    "SeriesTag",
                    r => r.HasOne<Tag>().WithMany()
                        .HasForeignKey("Tagid")
                        .HasConstraintName("fk_st_tags"),
                    l => l.HasOne<Series>().WithMany()
                        .HasForeignKey("Seriesid")
                        .HasConstraintName("fk_st_series"),
                    j =>
                    {
                        j.HasKey("Seriesid", "Tagid").HasName("series_tags_pkey");
                        j.ToTable("series_tags");
                        j.IndexerProperty<int>("Seriesid").HasColumnName("seriesid");
                        j.IndexerProperty<int>("Tagid").HasColumnName("tagid");
                    });
        });

        modelBuilder.Entity<Tag>(entity =>
        {
            entity.HasKey(e => e.Tagid).HasName("tags_pkey");

            entity.ToTable("tags");

            entity.Property(e => e.Tagid).HasColumnName("tagid");
            entity.Property(e => e.Tagname)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("tagname");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Userid).HasName("users_pkey");

            entity.ToTable("users");

            entity.HasIndex(e => e.Email, "UQ__users__AB6E61646AEA9275").IsUnique();

            entity.HasIndex(e => e.Username, "UQ__users__F3DBC57236049A8F").IsUnique();

            entity.Property(e => e.Userid).HasColumnName("userid").ValueGeneratedOnAdd().UseIdentityColumn();
            entity.Property(e => e.Createdat)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdat");
            entity.Property(e => e.Email)
                .HasMaxLength(255)
                .HasColumnName("email");
            entity.Property(e => e.Fullname)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("fullname");
            entity.Property(e => e.Isdeleted)
                .HasDefaultValue(false)
                .HasColumnName("isdeleted");
            entity.Property(e => e.Passwordhash)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("passwordhash");
            entity.Property(e => e.Roleid).HasColumnName("roleid");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("username");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.Roleid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("users_roleid_fkey");
        });

        modelBuilder.Entity<UserToken>(entity =>
        {
            entity.HasKey(e => e.Tokenid).HasName("PK__user_tok__AC17DF2F17E93E88");

            entity.ToTable("user_tokens");

            entity.HasIndex(e => e.Token, "UQ__user_tok__CA90DA7A7B2803E3").IsUnique();

            entity.Property(e => e.Tokenid).HasColumnName("tokenid");
            entity.Property(e => e.Expiresat)
                .HasColumnType("datetime")
                .HasColumnName("expiresat");
            entity.Property(e => e.Isrevoked)
                .HasDefaultValue(false)
                .HasColumnName("isrevoked");
            entity.Property(e => e.Token)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("token");
            entity.Property(e => e.Userid).HasColumnName("userid");

            entity.HasOne(d => d.User).WithMany(p => p.UserTokens)
                .HasForeignKey(d => d.Userid)
                .HasConstraintName("FK__user_toke__useri__03F0984C");
        });

        modelBuilder.Entity<WeeklyRanking>(entity =>
        {
            entity.HasKey(e => e.Rankingid).HasName("weekly_rankings_pkey");

            entity.ToTable("weekly_rankings");

            entity.HasIndex(e => new { e.Seriesid, e.IssueNumber, e.IssueYear }, "unique_series_weekly_evaluation").IsUnique();

            entity.Property(e => e.Rankingid).HasColumnName("rankingid");
            entity.Property(e => e.Calculatedat)
                .HasColumnType("datetime")
                .HasColumnName("calculatedat");
            entity.Property(e => e.Inputtedbyid).HasColumnName("inputtedbyid");
            entity.Property(e => e.Isbottomrank)
                .HasDefaultValue(false)
                .HasColumnName("isbottomrank");
            entity.Property(e => e.IssueNumber).HasColumnName("issue_number");
            entity.Property(e => e.IssueYear).HasColumnName("issue_year");
            entity.Property(e => e.Rankposition).HasColumnName("rankposition");
            entity.Property(e => e.Recordedat)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("recordedat");
            entity.Property(e => e.Seriesid).HasColumnName("seriesid");
            entity.Property(e => e.Votecount)
                .HasDefaultValue(0)
                .HasColumnName("votecount");

            entity.HasOne(d => d.Inputtedby).WithMany(p => p.WeeklyRankings)
                .HasForeignKey(d => d.Inputtedbyid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("weekly_rankings_inputtedbyid_fkey");

            entity.HasOne(d => d.Series).WithMany(p => p.WeeklyRankings)
                .HasForeignKey(d => d.Seriesid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("weekly_rankings_seriesid_fkey");
        });

        modelBuilder.Entity<BoardEvaluationDetail>(entity =>
        {
            entity.HasKey(e => e.DetailId);

            entity.ToTable("board_evaluation_details");

            entity.Property(e => e.DetailId).HasColumnName("detail_id");
            entity.Property(e => e.EvaluationId).HasColumnName("evaluation_id");
            entity.Property(e => e.EbId).HasColumnName("eb_id");
            
            entity.Property(e => e.StoryScore)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("story_score");
            entity.Property(e => e.ArtScore)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("art_score");
            entity.Property(e => e.CharacterScore)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("character_score");
            entity.Property(e => e.CommercialScore)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("commercial_score");
            entity.Property(e => e.PacingScore)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("pacing_score");
            entity.Property(e => e.Feedback).HasColumnName("feedback");
            entity.Property(e => e.EvaluatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("evaluated_at");
            entity.Property(e => e.AverageScore)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("average_score")
                .HasComputedColumnSql("((((([story_score]+[art_score])+[character_score])+[commercial_score])+[pacing_score])/(5.0))", stored: false);

            entity.Property(e => e.Isdeleted)
                .HasDefaultValue(false)
                .HasColumnName("isdeleted");

            entity.HasOne(d => d.Eb).WithMany()
                .HasForeignKey(d => d.EbId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_board_evaluation_details_eb");

            entity.HasOne(d => d.Evaluation).WithMany(p => p.BoardEvaluationDetails)
                .HasForeignKey(d => d.EvaluationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_board_evaluation_details_evaluation");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}