// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class AssistantProfile
{
    public int AssistantProfileId { get; set; }

    public int Userid { get; set; }

    public string AvatarUrl { get; set; }

    public string PortfolioUrl { get; set; }

    public string PhoneNumber { get; set; }

    public bool? IsAvailable { get; set; }

    public string Skills { get; set; }

    public string SoftwareUsed { get; set; }

    public string BankName { get; set; }

    public string BankAccountNumber { get; set; }

    public string BankAccountName { get; set; }

    public DateTime? Updatedat { get; set; }

    public virtual User User { get; set; }
}