// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class BoardEvaluation
{
    public int Evaluationid { get; set; }

    public int Seriesid { get; set; }

    public int Inputtedbyid { get; set; }

    public decimal StoryScore { get; set; }

    public decimal ArtScore { get; set; }

    public decimal CharacterScore { get; set; }

    public decimal CommercialScore { get; set; }

    public decimal PacingScore { get; set; }

    public decimal? AverageScore { get; set; }

    public string FinalDecision { get; set; }

    public string ApprovedPublishFormat { get; set; }

    public string Feedback { get; set; }

    public DateTime? Evaluatedat { get; set; }

    public virtual User Inputtedby { get; set; }

    public virtual Series Series { get; set; }
    public virtual ICollection<BoardEvaluationDetail> BoardEvaluationDetails { get; set; }
    = new List<BoardEvaluationDetail>();
}