// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class Chapter
{
    public int Chapterid { get; set; }

    public int Seriesid { get; set; }

    public int Chapternumber { get; set; }

    public string Title { get; set; }

    public DateTime Deadline { get; set; }

    public string Status { get; set; }

    public DateTime? Createdat { get; set; }

    public bool? Isdeleted { get; set; }

    public virtual ICollection<Page> Pages { get; set; } = new List<Page>();

    public virtual Series Series { get; set; }
}