// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class Genre
{
    public int Genreid { get; set; }

    public string Genrename { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Series> Series { get; set; } = new List<Series>();
}