// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class IssueResource
{
    public int Resourceid { get; set; }

    public int Issueid { get; set; }

    public string Filename { get; set; }

    public string Fileurl { get; set; }

    public DateTime? Uploadedat { get; set; }

    public virtual PageIssue Issue { get; set; }
}