// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class MangakaAssistant
{
    public int ContractId { get; set; }

    public int MangakaId { get; set; }

    public int AssistantId { get; set; }

    public decimal SalaryAmount { get; set; }

    public string SalaryType { get; set; }

    public string ContractTerms { get; set; }

    public string Status { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public DateTime? Createdat { get; set; }

    public virtual User Assistant { get; set; }

    public virtual User Mangaka { get; set; }
    public bool? Isdeleted { get; set; }
}