// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class MangakaProfile
{
    public int MangakaProfileId { get; set; }

    public int Userid { get; set; }

    public string PenName { get; set; }

    public string AvatarUrl { get; set; }

    public string Bio { get; set; }

    public string PhoneNumber { get; set; }

    public string BankName { get; set; }

    public string BankAccountNumber { get; set; }

    public string BankAccountName { get; set; }

    public DateTime? Updatedat { get; set; }

    public virtual User User { get; set; }
}