// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class Notification
{
    public int Notificationid { get; set; }

    public int Userid { get; set; }

    public int? Seriesid { get; set; }

    public string Title { get; set; }

    public string Message { get; set; }

    public bool? Isread { get; set; }

    public DateTime? Createdat { get; set; }

    public string Referencetype { get; set; }

    public int? Referenceid { get; set; }

    public virtual Series Series { get; set; }

    public virtual User User { get; set; }
}