// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class PageIssue
{
    public int Issueid { get; set; }

    public int Pageid { get; set; }

    public int CreatedById { get; set; }

    public int? AssignedToId { get; set; }

    public string IssueType { get; set; }

    public string WorkCategory { get; set; }

    public int BoxX { get; set; }

    public int BoxY { get; set; }

    public int BoxWidth { get; set; }

    public int BoxHeight { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public DateTime? Deadline { get; set; }

    public DateTime? Createdat { get; set; }

    public DateTime? Completedat { get; set; }

    public bool? Isdeleted { get; set; }

    public virtual User AssignedTo { get; set; }

    public virtual User CreatedBy { get; set; }

    public virtual ICollection<IssueResource> IssueResources { get; set; } = new List<IssueResource>();

    public virtual Page Page { get; set; }

}