// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class Pagelayer
{
    public int Layerid { get; set; }

    public int Pageid { get; set; }

    public int Uploaderid { get; set; }

    public int? Issueid { get; set; }

    public string Layername { get; set; }

    public string Fileurl { get; set; }

    public int? Zindex { get; set; }

    public int? Versionnumber { get; set; }

    public bool? Isvisible { get; set; }

    public DateTime? Createdat { get; set; }

    public virtual PageIssue Issue { get; set; }

    public virtual Page Page { get; set; }

    public virtual User Uploader { get; set; }
}