// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class Page
{
    public int Pageid { get; set; }

    public int Chapterid { get; set; }

    public int Pagenumber { get; set; }

    public string Status { get; set; }

    public bool? Isdeleted { get; set; }

    public virtual Chapter Chapter { get; set; }

    public virtual ICollection<PageIssue> PageIssues { get; set; } = new List<PageIssue>();

    public virtual ICollection<Pagelayer> Pagelayers { get; set; } = new List<Pagelayer>();
}