// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class Series
{
    public int Seriesid { get; set; }

    public string Title { get; set; }

    public string Synopsis { get; set; }

    public int Mangakaid { get; set; }

    public int Tantoueditorid { get; set; }

    public string Publishformat { get; set; }

    public string Status { get; set; }

    public string Proposalfileurl { get; set; }

    public DateTime? Createdat { get; set; }

    public DateTime? Approvedat { get; set; }

    public bool? Isdeleted { get; set; }

    public virtual ICollection<BoardEvaluation> BoardEvaluations { get; set; } = new List<BoardEvaluation>();

    public virtual ICollection<Chapter> Chapters { get; set; } = new List<Chapter>();

    public virtual User Mangaka { get; set; }

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual User Tantoueditor { get; set; }

    public virtual ICollection<WeeklyRanking> WeeklyRankings { get; set; } = new List<WeeklyRanking>();
}