// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class Tag
{
    public int Tagid { get; set; }

    public string Tagname { get; set; }

    public virtual ICollection<Series> Series { get; set; } = new List<Series>();
}