// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class User
{
    public int Userid { get; set; }

    public string Username { get; set; }

    public string Passwordhash { get; set; }

    public string Fullname { get; set; }

    public string Email { get; set; }

    public int Roleid { get; set; }

    public DateTime? Createdat { get; set; }

    public bool? Isdeleted { get; set; }

    public virtual AssistantProfile AssistantProfile { get; set; }

    public virtual ICollection<BoardEvaluation> BoardEvaluations { get; set; } = new List<BoardEvaluation>();

    public virtual ICollection<MangakaAssistant> MangakaAssistantAssistants { get; set; } = new List<MangakaAssistant>();

    public virtual ICollection<MangakaAssistant> MangakaAssistantMangakas { get; set; } = new List<MangakaAssistant>();

    public virtual MangakaProfile MangakaProfile { get; set; }

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<PageIssue> PageIssueAssignedTos { get; set; } = new List<PageIssue>();

    public virtual ICollection<PageIssue> PageIssueCreatedBies { get; set; } = new List<PageIssue>();

    public virtual ICollection<Pagelayer> Pagelayers { get; set; } = new List<Pagelayer>();

    public virtual Role Role { get; set; }

    public virtual ICollection<Series> SeriesMangakas { get; set; } = new List<Series>();

    public virtual ICollection<Series> SeriesTantoueditors { get; set; } = new List<Series>();

    public virtual ICollection<WeeklyRanking> WeeklyRankings { get; set; } = new List<WeeklyRanking>();

    public virtual ICollection<UserToken> UserTokens { get; set; } = new List<UserToken>();
}