// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace Entities.Models;

public partial class UserToken
{
    public int Tokenid { get; set; }

    public int Userid { get; set; }

    public string Token { get; set; }

    public bool? Isrevoked { get; set; }

    public DateTime Expiresat { get; set; }

    public virtual User User { get; set; }
}
