// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class WeeklyRanking
{
    public int Rankingid { get; set; }

    public int Seriesid { get; set; }

    public int IssueNumber { get; set; }

    public int IssueYear { get; set; }

    public int? Votecount { get; set; }

    public int Inputtedbyid { get; set; }

    public DateTime? Recordedat { get; set; }

    public int? Rankposition { get; set; }

    public bool? Isbottomrank { get; set; }

    public DateTime? Calculatedat { get; set; }

    public virtual User Inputtedby { get; set; }

    public virtual Series Series { get; set; }
}